INSERT INTO CLIENTE (ID, NOME, SOBRENOME, TELEFONE, DATA_NASCIMENTO, CPF) VALUES (888, 'ALUNO', 'ESCOLA', '', CURRENT_DATE, '');
INSERT INTO CLIENTE (ID, NOME, SOBRENOME, TELEFONE, DATA_NASCIMENTO, CPF) VALUES (999, 'ALUNO', '2', '', CURRENT_DATE, '');

INSERT INTO USUARIO (ID, NOME, SOBRENOME, TELEFONE, DATA_NASCIMENTO, CPF, EMAIL, SENHA) VALUES (888, 'USUARIO', 'ESCOLA', '', CURRENT_DATE, '', 'email@test.com', '$2a$10$qtmoNqNRSevN5RnViKqXX.jCCzWWxD28kVdK9zyRGzBhY21oSP712');